language: c

dist: trusty
sudo: false

compiler:
    - clang
    - gcc

env:
    - BUILD=cmake BUILD_TYPE=Debug
    - BUILD=cmake BUILD_TYPE=Release
    - BUILD=autotools

script: |
    case $BUILD in
    cmake)
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make && make test
        ;;
    autotools)
        autoreconf -i && ./configure && make && make check
        ;;
    esac
