image:
  - Visual Studio 2019

cache:
  - c:\users\appveyor\clcache
  - c:\local\boost_1_69_0

environment:
  BOOST_ROOT: C:\local\boost_1_69_0
  BOOST_LIBRARYDIR: C:\local\boost_1_69_0\lib64-msvc-14

init:
  - set PATH=c:\Python37;c:\Python37\Scripts;%PATH%
  - pip install clcache

before_build:
  - clcache -s

install:
  - ps: Write-Host "Checking for Boost 1.69.0 x64...";$boostdir  = Test-Path $Env:BOOST_ROOT;If ($boostdir -eq $False) {Write-Host "Downloading Boost 1.69.0 x64...";$exePath = "$Env:TEMP\boost_1_69_0-msvc-14.1-64.exe";(New-Object Net.WebClient).DownloadFile('https://bintray.com/boostorg/release/download_file?file_path=1.69.0%2Fbinaries%2Fboost_1_69_0-msvc-14.1-64.exe', $exePath);Write-Host "Installing Boost 1.69.0 x64...";cmd /c start /wait "$exePath" /verysilent;del $exePath};Write-Host "Boost 1.69.0 x64 installed!" -ForegroundColor Green

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 .. -DARCH=default -DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64
  - MSBuild 2ACoin.sln /p:CLToolExe=clcache.exe /p:CLToolPath=c:\Python37\Scripts\ /p:Configuration=Release /m
  - src\Release\cryptotest.exe

after_build:
  - clcache -s
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir 2ACoin-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe 2ACoin-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE 2ACoin-%APPVEYOR_REPO_TAG_NAME%
  - 7z a 2ACoin-%APPVEYOR_REPO_TAG_NAME%-windows.zip 2ACoin-%APPVEYOR_REPO_TAG_NAME%
  - copy 2ACoin-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: 2ACoin-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: 2ACoinRelease

deploy:
  - provider: GitHub
    auth_token:
      secure: AOtonaRkm/3AeJ3y3TsadNYz9ksJPwaN/hNBkzDkYTsT0jYmeBz9mhznpIKpQIlr
    artifact: 2ACoinRelease
    draft: true
    prerelease: false
    on:
      appveyor_repo_name: 2acoin/2acoin
      appveyor_repo_tag: true

  - provider: S3
    access_key_id:
      secure: oD6MDz0g41DzeifRYmKpD+v43huRZnUk6IguyYvNTiFItzEYaMJelTcV+A04OU4b7NQRdGRHNxW+5AorxfICgFPAIKCbBZ09xv+0s0UV+kjmjqIihnS1GGsh+oyVRX/8AKUSViD5z1YFcsCNbIlRRoGgovcaM8Jvmh7s0wjyFvVaVcAPuoXM/6M0aNsjzklaHbIfc7APEMEgQhixUEiiX3Lt4KoycWPqonYUhaA4w4xZsped3a8B42oghHlxR93mCWIuSpHS6VU4i8SFJttX6cNIJkKYLKzBj2Ju+PiX/vL51jEV/uXVM8sMO9PEkEmZx4gmXv5hviGElgmDcWkyIv/zEEjm3wTkJqOCYQfYOle7nak+fPu2xqwG9Ov78cWEF0swa5TOPaJR4+TUO3NyYThey0+JGAIPpMK0DqRpk3lTfHRcX00A8D5kxwf9dJqDEhce1FofjG4Tit2ODr8azHYEGyJLna3Fw47bMPLFaghzE6G82TTlx4HrHHZsGgZue0W3t9WuKr5jL1KL4dAczFtOXuvfLd8u0KyE/jPe/1tkluT79WJGOEyAI0W9gtG4hqLbpcrtFb5EwNWddgqjpuautaqfQyCeNtVHNVvnNFdHgUHI0CuxkmcdXHIrS6gyfjwWAIoHx0cv3u7az/J37Pt/Rx1qyzizuX40Sr45DoWeg4mg0oW8kkqDF6FYkbZjzQU4oUM1oukbJKk+lYVzivB2vg699dqpdo3kLkSXXFaOHU2IKjM1OS1NXUJtjXAZwU81MfaO1uiDy8tX+SRTVw7/qhmVwH8Q6zUf2bCzgmiHXlRAvkSKF55u/uy9l7GgRIrzslfnT5zf9U7VLGR+JDh6buvMinv8gTUf8g7XGVrlAIyWrzpaS7JbBtN+ELME4vXNHcZ8Xn7rQvKWWpTmRQ==
    secret_access_key:
      secure: Qna9u//WWfhbOA2xDaBNvjk9geKTvHyIolafGxk3ElWNBmz+nBuqL+b08DAsjp14vuA4GHpO6EF+TOi9JB4COF3c1WzD7KUbjXkYkpYrpByASfsLwpK6sBB7cJJVi1Wi1vwXQ1ligcPT1yaUv94ru41/Az56Al+uCGbbHpX/0nlu22NlSh6EAfJJG9D/SWgUFCVvy+Ls21dgZVhQ0fNsCdAxTjpaPV3lkI47issPr5lVtkVVtsxhLFZMork4RKuYWJtJ8CDTD549tWKqkv4NZhaIXRq1BzoNO/un/Uyvz0MRWQUp3cbU5VAr/d0CgFfjZ/1wJRtKfrhcWXJpBq7wWScGCPCFIcJXBKsqo+jB50hboar2aoRowJFrY5L4I3Oq4InUTJHwxIy7CeZC7wOIkJ9XFIEzMfXYqsisR44EURJbepJESM2lFj4trElYrolWSBeUXeI81iX/e4EDkFYu/M7ilqWJmZqtKDVbat2cpUKWVOlpwl6JOwkzZoYqzQIrc9PU/ppgDUEqVNt7vyVGHOLOzLI5Mwg2zUpIJaTm1/ZqWO+veYx5uMuiS5Vhiwpx/pR57iOWp5pGBB8LQrrn5T/OShw/zPL/I3lCaoWIVOseVIMLqKKoIRsjND0pmGhOelSCiS6T1iEsXHd0RaUXmGs7UiY147+S5qmgOCc66gwl3W7hIHGgEhJnjsALd/rA1iQPrDVtzHwAUWG43CSAeH6Ipl2AmUlOOVG4S8lsR8h0rcXiuzz1uvTwzWi7Lj16+if8WqUXZT+Sq3TDqJiLpm2V9MIyHienYW1SB4AXGOH9Z1lcxsGqnl/6+VGWPqXSMeT0wVEozBFiLIwJo8L1i6mZmOldHHRi0AIjW88oBT1Cz7nMyDvmJJYQJoiFDA9Vv1NFB9Nbifb8Nh/u2Pt0ew==
    bucket: olk-2acoin
    region: us-east-1
    set_public: true
    folder: 2acoin
    artifact: 2ACoinRelease
    on:
      appveyor_repo_name: 2acoin/2acoin
