os: Visual Studio 2017

cache: c:\users\appveyor\clcache

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14

init:
  - set PATH=c:\Python37;c:\Python37\Scripts;%PATH%
  - pip install clcache

before_build:
  - clcache -s

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" .. -DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64
  - MSBuild 2ACoin.sln /p:CLToolExe=clcache.exe /p:CLToolPath=c:\Python37\Scripts\ /p:Configuration=Release /m
  - src\Release\cryptotest.exe

after_build:
  - clcache -s
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir 2ACoin-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe 2ACoin-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE 2ACoin-%APPVEYOR_REPO_TAG_NAME%
  - 7z a 2ACoin-%APPVEYOR_REPO_TAG_NAME%-windows.zip 2ACoin-%APPVEYOR_REPO_TAG_NAME%
  - copy 2ACoin-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: 2ACoin-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: 2ACoinRelease

deploy:
  - provider: GitHub
    auth_token:
      secure: AOtonaRkm/3AeJ3y3TsadNYz9ksJPwaN/hNBkzDkYTsT0jYmeBz9mhznpIKpQIlr
    artifact: 2ACoinRelease
    draft: true
    prerelease: false
    on:
      appveyor_repo_name: 2acoin/2acoin
      appveyor_repo_tag: true

  - provider: S3
    access_key_id:
      secure: f6E1aAWppFCM/EWOe8+SHQEf50Dc9KXQSCocQkaedZ4=
    secret_access_key:
      secure: 465c0S53qpmIPFTS29OyHNABI5O1I0C40JYYB5TRu84ztrwHECUk1fN8a6Vh7rwE
    bucket: olk-2acoin
    region: us-east-1
    set_public: true
    folder: 2acoin
    artifact: 2ACoinRelease
    on:
      appveyor_repo_name: 2acoin/2acoin
