sudo: false
language: cpp
cache:
 ccache: true
 directories:
    - /home/travis/toolchain

matrix:
  include:

  # Ubuntu, g++-8
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - g++-8
          - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  # Ubuntu, g++-7
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - g++-7
          - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - STRIP="strip"

  # Ubuntu, clang-6
  - os: linux
    dist: trusty
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - clang-6.0
          - libstdc++-7-dev
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - LABEL="linux-clang-6"
    - STRIP="strip"

  # Arm (aarch64) cross compile
  - os: linux
    dist: trusty
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"

before_install:
- eval $MATRIX_EVAL

script:
- eval $MATRIX_EVAL
# If we're cross compiling aarch64, make sure our build enivornment is setup
# we do this in the script stage because this happens after the repo is cloned
- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake -DARCH=default -DCMAKE_BUILD_TYPE=Release -DSTATIC=true ..
- make -j2
- if [[ "$LABEL" != "aarch64" ]]; then ./src/cryptotest ; fi

before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="2ACoind miner zedwallet 2acoin-service cryptotest wallet-api wallet-upgrader"
- ${STRIP} ${TARGETS}
- rm -rf 2ACoin-${TRAVIS_TAG} 
- mkdir 2ACoin-${TRAVIS_TAG}
- cp ${TARGETS} 2ACoin-${TRAVIS_TAG}/
- cp ../../LICENSE 2ACoin-${TRAVIS_TAG}/
- tar cvfz 2ACoin-${TRAVIS_TAG}-${LABEL}.tar.gz 2ACoin-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp 2ACoin-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- cd ..

deploy:
  - provider: releases
    api_key:
      secure: KOIIPdqHmlGDIuKTgvgxTNTfw50cALzBTEAmf+nXmsrTE6VluQoUDzO6mWehQkfVossXb/0CkvKDeIEpl91dMGDb0BmZeTQA075/NjWpcntnoFv1c9pE6KkJEVBJ/DWUON+LWtf2aI9/rSiF6mta4VEyGEXbeaqZpbDfLhGY0GAtGzHqwl9ZDkwIe+nYxpchGd+F/s6MHkHfzwF7SuiKuBSSthrbbtBCUf2+LcZzI42Io/CpTS6Dm2GsCJ09w0XnfCi19tPpN1GcPnHmdPmozg0wCopccJI7N9GHQfNtANAc7rU92x3aCZon3AxHqXUvN0BOH5VYur9QZGpJhINf0ehkvVkMUUqvhjpuSMUqXcnDaqE4FauG3pfQneZQAOrq0lbPUIDEfvP4Hg3ab1u062nZp9pnCoIJr+/pojzDFhfTYUZMNTG1NyU/2Aacm6IvmeBkTyJXYvsM8yJTPKrOqi6Hz6CsC4X+b2bzYbmRFzh49pvrU1OeuqVqVw+ktOhRgx+oOsj0OrN8wLL0sQ9mTCGr0BIcVJTi5HHpLPt7jYgYnSlUwu+p0lRrhoR6xyI2OqvHrKcu1HM9ZqItSLKVX/zoSmnyslb0A7rPJ6P6mhRb6w/bFCHO+vXhc0dMkZZTNGzOeteOGFTchV6vktCl4Osam3N/46+bFcUZijj0TBw=
    file:
      - 2ACoin-${TRAVIS_TAG}-${LABEL}.tar.gz
    skip_cleanup: true
    draft: true
    on:
      repo: 2acoin/2acoin
      tags: true
      condition: "$_DEPLOYABLE = true"

  - provider: s3
    access_key_id:
      secure: FVef7iQADevPocE/FcNzHvYcWWc1z9xn1DG676qlBlPv5V0zPrWRfb4YyD274N9Lbu5nCXMpGdnju3ZwLdB0OCTdi/iquiiyfTIzVaPOY3dmQe8waT0sLZe+nfmA7dmDUxHtVpUEaKApv3vLxsSwNcNyaLxbgr/BK2NuXZ6Lf7Otg15i7Jx9SzQFbT02b8fpMqsQa9QhulfJBpkSWfIlCUafT7I3m9p6tES1nNuQrJZ/PcmrXehGGuxziw1rzs6ZGy/bGOGBHXfbEkGNEGsxl5hMzxv+CgNKQa8Bk2NpfsEMXP+kqFyBVrO4wNEIvz0NsOv+Rn5nVGyqGTvwvAiyWdQdMwaftzgwZlIZYjfBZjf3LWryD/dstfJeDyU0Y3+HwtoaL6g0IvKP+JGKTvMYphIdKrLsaEvIIh83q6xrqIxk7rVjJU8nQRWqr+SyXVepPC0pdpGW6lM5sschcZTyokF9jNGoMNYxVf2NUxntlXKEaxKszrWrYqcjywaCLAVvqxIfsjXw310tBOP+kK5G2/hqqJHLGi3TBqOSD2nWp08ZyDnFrwJLgnXc8NFgrU+i7HFqG4wIwoHHwJOJRgf4w48rZnYuLKY/VvYHL3l6etys0EO8QdIoG3noGAPxPixwsFQB43CkNtoRrLrxvVgfEZ0phh9KYPQ6ZE5EgMqs3Jg=
    secret_access_key:
      secure: GjQH2bPD4vBPbM2D1WkrZpU881MNouGmF4DQEGbLrfRqJj5zCoa5jCdLPV4s878iPiIzhwpsaHu7RgK4lGCy2cLHw7YGBzt47m7DNEUB/ERJIBy5ITXPX+XkUyJ0jQJXlgdF+oV37VjBSILtD2adx1qYqxDDkE/twYxbOO9MxHmsKh5ZICion4wXCk7FDEAj6w9DBQGUmrOA3g/dDk9v3/xlyqbqAzFtyMVUA1aSoMiHYpDX/yucXr47hukHTp+GGFRvGk8f7p6aJYZjAgfeiMWda/RchaL4sbI2WVrLWJW+wr54IxeSwNDdG8vlw4XGjVyWUtq3WXpa3y7qavAHM9Q5fJgdrutmzVecHCbbNoZoOwZ9Fv2PfsGZAo4jiJ1N0R9ZhVtFswAAl8w+2uNLP3LzcDs5+Dy6/MH2qf89VsMVEgy18LI6vmf+z64G10vm30BLYqtNWIl1Igjrjya7u2nEFDJui24Kuo20ImY+ZS+5Bcg0E4dlyV5QLd/EKoxLq9PuUHQjLsQliEALnEsZnxEJVSoXUhaRp7/BNKEuK717i7pkc2pIGu1xZq1ocOBBrSmkw6Ua5jPw3GY4/5XhbPUUYPttR3iod3ts0ciF9rwMKdBGoWzqY1sOhPPXrocEduvBu/DZ4iRVNeP3bNy6r/z+5Gx6Ip0NS9g82bb+NXQ=
    bucket: olk-2acoin
    skip_cleanup: true
    region: us-east-1
    upload-dir: 2acoin
    local-dir: src/builds
    on:
      repo: 2acoin/2acoin
      all_branches: true
