sudo: false
language: cpp
cache:
 ccache: true
 directories:
    - /home/travis/toolchain

matrix:
  include:

  # Ubuntu, g++-8
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - g++-8
          - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="false"
    - STRIP="strip"

  # Ubuntu, g++-7
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - g++-7
          - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - STRIP="strip"

  # Ubuntu, clang-6
  - os: linux
    dist: trusty
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - clang-6.0
          - libstdc++-7-dev
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - LABEL="linux-clang-6"
    - STRIP="strip"

  # Arm (aarch64) cross compile
  - os: linux
    dist: trusty
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="false"
    - STRIP="aarch64-linux-gnu-strip"

before_install:
- eval $MATRIX_EVAL

script:
- eval $MATRIX_EVAL
# If we're cross compiling aarch64, make sure our build enivornment is setup
# we do this in the script stage because this happens after the repo is cloned
- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake -DARCH=default -DCMAKE_BUILD_TYPE=Release -DSTATIC=true ..
- make -j2
- if [[ "$LABEL" != "aarch64" ]]; then ./src/cryptotest ; fi

before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="2ACoind miner zedwallet 2acoin-service cryptotest wallet-api wallet-upgrader"
- ${STRIP} ${TARGETS}
- rm -rf 2ACoin-${TRAVIS_TAG} 
- mkdir 2ACoin-${TRAVIS_TAG}
- cp ${TARGETS} 2ACoin-${TRAVIS_TAG}/
- cp ../../LICENSE 2ACoin-${TRAVIS_TAG}/
- tar cvfz 2ACoin-${TRAVIS_TAG}-${LABEL}.tar.gz 2ACoin-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp 2ACoin-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- cd ..

deploy:
  - provider: releases
    api_key:
      secure: KOIIPdqHmlGDIuKTgvgxTNTfw50cALzBTEAmf+nXmsrTE6VluQoUDzO6mWehQkfVossXb/0CkvKDeIEpl91dMGDb0BmZeTQA075/NjWpcntnoFv1c9pE6KkJEVBJ/DWUON+LWtf2aI9/rSiF6mta4VEyGEXbeaqZpbDfLhGY0GAtGzHqwl9ZDkwIe+nYxpchGd+F/s6MHkHfzwF7SuiKuBSSthrbbtBCUf2+LcZzI42Io/CpTS6Dm2GsCJ09w0XnfCi19tPpN1GcPnHmdPmozg0wCopccJI7N9GHQfNtANAc7rU92x3aCZon3AxHqXUvN0BOH5VYur9QZGpJhINf0ehkvVkMUUqvhjpuSMUqXcnDaqE4FauG3pfQneZQAOrq0lbPUIDEfvP4Hg3ab1u062nZp9pnCoIJr+/pojzDFhfTYUZMNTG1NyU/2Aacm6IvmeBkTyJXYvsM8yJTPKrOqi6Hz6CsC4X+b2bzYbmRFzh49pvrU1OeuqVqVw+ktOhRgx+oOsj0OrN8wLL0sQ9mTCGr0BIcVJTi5HHpLPt7jYgYnSlUwu+p0lRrhoR6xyI2OqvHrKcu1HM9ZqItSLKVX/zoSmnyslb0A7rPJ6P6mhRb6w/bFCHO+vXhc0dMkZZTNGzOeteOGFTchV6vktCl4Osam3N/46+bFcUZijj0TBw=
    file:
      - 2ACoin-${TRAVIS_TAG}-${LABEL}.tar.gz
    skip_cleanup: true
    draft: true
    on:
      repo: 2acoin/2acoin
      tags: true
      condition: "$_DEPLOYABLE = true"

  - provider: s3
    access_key_id:
      secure: hUG5oW/beg3QlT49zgnp0Ie6HZqSk6ZrQJAFRZLDPwpu1g1QlN/gk6dfGEX3mBaiWf/Ap2nG/B1SFL8iNkppnzX9aqe8rNae3b4gzbjEs/wJu0+5ntUpt9UpGTupgcRiC7BDJ+k4w4J79MTnFYtcrUPn0vHZhqV3YvZr+zQe4RSfpMmQpTeI22hHvo9dyYuaY1DD6Vdf1jOMVydAE3raMW9BmKLpeu59ZOr6T5A9IhVffGNxxZKrG6DcSSe/J9tTZcT6pciOzVTuQEUjotk+psB25y7kd8dD4DluOP1NyY+/jSk88yMUygI1PZerWzGDrfm/PmBxqUIhu0R02/pTtfXdgUGjtbjHAy7Is63kf0TSwCOLfPHHptvxn0aKUzlUbuoBEsvo7SXS/AO42CHdvui+Ygl9xipVI+LciJKCCzRrSYnGFNP4BUweK0n0fUuCYjzl/VcDugs5oAZ0+OniJDfd0RfPeedufrzWlITA9pshxBzORv524DHCqayqTrZYrCErCekZHxYNpuyDIB5Tq0GxzjJQpnEhgxrh0vkugV+09t1sMfHTyJz+Sgp2lxITwnHF0KnkPDnSSku9Ftf6qx3lh+SZFgyu/bRutMPxDALWfVdRglDe6jAvzNtOHFoM77K0H2RlcbQulhjBOjsmYRpdtUCzL/5akb3Na4fr45s=
    secret_access_key:
      secure: GiD22ph/8kCPMtCLxHBFOTTKgjJS2Wyoz9/fTELPsfNDeYYLMz0LvKzKh0L626/4Vew0B7tIeZ2ItPuOTjCuVqvj6vVH4CnzqKaadli8GGhDkQ1/PGBeXKzTywOsk2pMoTpzQ8ePx7QAQmmW2oXYixDT9sdhCLxVpjOAXQfw+pPRmaQFREgwTBtBhpZiEbujxdfjGHG3bzTJph9GeXrqtHaBNdJ8vy6409Qk/6malNy6ACDnCuklRCmWGtTgrmgUXAQxS4to3qaSAkuSVoZ69ZQ1VCx8ih+lIA8yBC2nCOSAeTM6obPiTTZWULtcifh9s1YOMt5t8buS1bhVFCOwqhvJwh3eOIf9HqhQwvxDqtc9Qc1a3Etmnt/Iwbcl6BvgBSxH12Qrbq9enlhAy6cyl3ObAs/FQ7qzisCPAiXAUP2dr+3/jnI2Fxyo4kFqL4Stf+inYBY6OXyHSI9DY4V7EA/YJB9wRkMzJsogO12Vo1j27Ih7v+5gqbd2otQZ97D/1ZoWYl2Ru2cdXFeM5gI6cbsyBJUN0WLJkDmz/Bqg2kYSCSzH+Kw4yRux79Cwwjn/yvQqSNNssY2qgI+416Nyw1aVGs9iZAxDk/G8enCGHc69rljh1HS/wNk/N8v3jbS1LPtxn45AiCvlrrsdz1RmUDLzMkMb5MUShCdm2yY8GDY=
    bucket: olk-2acoin
    skip_cleanup: true
    region: us-east-1
    upload-dir: 2acoin
    local-dir: src/builds
    on:
      repo: 2acoin/2acoin
      all_branches: true
